// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rec-card/PremiumDark.tsx": () => import("../components/mockups/rec-card/PremiumDark.tsx"),
  "./components/mockups/rec-card/StructuredPro.tsx": () => import("../components/mockups/rec-card/StructuredPro.tsx")
};
